# Clé unique du projet (à adapter selon la configuration de votre serveur Sonar)
sonar.projectKey=skillhub-groupe-bc03
sonar.projectName=SkillHub - Groupe BC03
sonar.projectVersion=1.0

# Organisation SonarCloud (obligatoire pour cloud)
sonar.organization=skillhub-groupe-bc03

# Dossiers contenant le code source à analyser
sonar.sources=frontend, services/auth, services/catalog, services/inscription

# Encodage des fichiers
sonar.sourceEncoding=UTF-8

# Exclusions : on ignore les dépendances et les fichiers générés
sonar.exclusions=**/node_modules/**, **/*.spec.js, **/*.test.js, **/dist/**, **/build/**

# Si vous avez des tests, vous pouvez spécifier le dossier de couverture de code
# sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,services/auth/coverage/lcov.info