sonar.projectKey=Andrimirana_skillhub-groupe-BC03
sonar.projectName=SkillHub - Groupe BC03
sonar.projectVersion=1.0
sonar.organization=andrimirana
sonar.host.url=https://sonarcloud.io

sonar.sourceEncoding=UTF-8

sonar.sources=frontend/src,services/auth-java/src/main/java,services/catalog/app,services/inscription/app
sonar.tests=services/auth-java/src/test,services/catalog/tests,services/inscription/tests

sonar.exclusions=\
**/node_modules/**,\
**/vendor/**,\
**/dist/**,\
**/build/**,\
**/coverage/**,\
**/storage/**,\
**/bootstrap/cache/**,\
**/database/migrations/**,\
**/database/factories/**,\
**/public/**,\
**/*.config.js,\
**/*.config.cjs,\
**/vite.config.js,\
**/composer.lock,\
**/package-lock.json

sonar.coverage.exclusions=\
**/tests/**,\
**/database/**,\
**/config/**,\
**/routes/**,\
frontend/src/main.jsx

sonar.java.binaries=services/auth-java/target/classes
