name: CI/CD Pipeline - SkillHub BC03

on:
  push:
    branches:
      - main
      - dev
  # C'est cette partie qui détecte les Pull Requests vers dev et main !
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - dev

jobs:
  tests-et-sonar:
    name: Tests, Coverage et SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Requis par SonarCloud pour lire tout l'historique Git

      - name: Configuration de PHP avec PCOV (pour le coverage)
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_mysql, bcmath, gd
          coverage: pcov # Extrêmement rapide pour générer le coverage !

      - name: Installation et Tests du Service Auth
        working-directory: ./services/auth
        run: |
          composer install --prefer-dist --no-progress
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate
          touch database/database.sqlite
          # On génère le fichier de couverture (coverage.xml)
          DB_CONNECTION=sqlite DB_DATABASE=database/database.sqlite php artisan test --coverage-clover=coverage.xml

      - name: Scan SonarCloud
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./services/auth
          args: >
            -Dsonar.projectKey=Andrimirana_skillhub-groupe-BC03
            -Dsonar.organization=andrimirana
            -Dsonar.php.coverage.reportPaths=coverage.xml
            -Dsonar.sources=app,routes
            -Dsonar.tests=tests